name: CI

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: actions/setup-node@master
              with:
                  node-version: "16.x"
            - run: npm ci
            - run: npm test
            - run: actions/deploy-pages@v2
              with:
                emit_telemetry: false
                token: ***
                timeout: 600000
                error_count: 10
                reporting_interval: 5000
                artifact_name: github-pages
                preview: false
